/**
 * Aliento Health — AI Draft Client
 *
 * Gateway client + prompt builders for the "AI-drafted, doctor-signed"
 * pipeline. Drafts are generated by a shared OpenCode serve gateway
 * (native protocol + Basic auth) and ALWAYS returned for review by the
 * signing practitioner before anything reaches a patient.
 *
 * Safety rules enforced here:
 *   1. Every user message is pseudonymised via `pseudonymizeText`
 *      before it leaves the server, and tokens are restored on the
 *      model's reply via `restoreTokens`.
 *   2. The system prompt forbids inventing facts, medications, or
 *      diagnoses and demands `[REVIEW]` markers on uncertainty.
 *   3. Every draft must be valid JSON; anything else throws.
 */

import { pseudonymizeText, restoreTokens } from './ai-pseudonymize'

// ─── Types ─────────────────────────────────────────────────────────────────

export interface DraftMedication {
  name: string
  dosage: string
  frequency: string
  duration: string
}

export interface SickNoteDraft {
  symptoms: string
  reason: string
}

export interface ScriptDraft {
  medications: DraftMedication[]
  instructions: string
}

export interface BlogDraft {
  title: string
  excerpt: string
  contentHtml: string
}

export type KnownPatientPii = {
  name?: string
  address?: string
}

// ─── Prompts ───────────────────────────────────────────────────────────────

const SHARED_SYSTEM_PROMPT =
  'You are drafting for a licensed medical practitioner (Dr Leegale Adonis, ' +
  'MBBCH/MBA/FCPHM/MMed/PhD) to review and sign. Never invent facts, ' +
  'medications, or diagnoses. Mark anything uncertain as [REVIEW]. ' +
  'Output ONLY valid JSON.'

const SICK_NOTE_INSTRUCTIONS = [
  'Task: summarise a patient sick-note request.',
  'Reply with ONLY this JSON shape: {"symptoms": "...", "reason": "..."}',
  '"symptoms" and "reason" must be professional-but-warm clinical summary sentences suitable for a sick note.',
  'Do NOT include the patient name in either field.',
].join('\n')

const SCRIPT_INSTRUCTIONS = [
  'Task: draft a prescription script for practitioner review.',
  'Reply with ONLY this JSON shape:',
  '{"medications": [{"name": "...", "dosage": "...", "frequency": "...", "duration": "..."}], "instructions": "..."}',
  'Never invent medication names beyond what the patient reported.',
  'Keep existing medication rows if plausible; suggest additions only when the questionnaire supports it (mark uncertain ones as [REVIEW]).',
].join('\n')

const BLOG_INSTRUCTIONS = [
  'Task: draft a health blog post.',
  'Reply with ONLY this JSON shape: {"title": "...", "excerpt": "...", "contentHtml": "..."}',
  '"contentHtml" must use ONLY <h2>, <p>, <ul> and <li> tags.',
].join('\n')

const BLOG_VOICE =
  'Write in the voice of: a knowledgeable friend who happens to be a doctor, ' +
  'explaining over tea — evidence-based, no jargon, warm but not fluffy.'

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Draft sick-note summary text from a raw questionnaire JSON string.
 * Patient PII is pseudonymised before sending and restored afterwards.
 */
export async function draftSickNote(
  questionnaireRaw: string,
  knownPii?: KnownPatientPii,
): Promise<SickNoteDraft> {
  const userMessage = [
    'Patient questionnaire (JSON):',
    trimQuestionnaire(questionnaireRaw),
    '',
    SICK_NOTE_INSTRUCTIONS,
  ].join('\n')

  const raw = await runDraft(userMessage, joinSystem(SICK_NOTE_INSTRUCTIONS), knownPii)
  return parseJsonDraft<SickNoteDraft>(raw)
}

/**
 * Draft a prescription script from a raw questionnaire JSON string plus
 * the patient's current medication rows. Medication names never leave
 * the set reported by the patient; uncertain suggestions are marked
 * `[REVIEW]` for the practitioner.
 */
export async function draftScript(
  questionnaireRaw: string,
  currentMeds: DraftMedication[],
  knownPii?: KnownPatientPii,
): Promise<ScriptDraft> {
  const userMessage = [
    'Patient questionnaire (JSON):',
    trimQuestionnaire(questionnaireRaw),
    '',
    'Current medication rows (JSON):',
    JSON.stringify(currentMeds),
    '',
    SCRIPT_INSTRUCTIONS,
  ].join('\n')

  const raw = await runDraft(userMessage, joinSystem(SCRIPT_INSTRUCTIONS), knownPii)
  return parseJsonDraft<ScriptDraft>(raw)
}

/**
 * Draft a blog post on `topic` in Dr Adonis' warm, evidence-based
 * voice, guided by excerpts of existing posts as style references.
 */
export async function draftBlogPost(
  topic: string,
  styleRefs: { title: string; content: string }[],
): Promise<BlogDraft> {
  const refs = styleRefs.slice(0, 3).map(
    (ref, index) =>
      `--- Style reference ${index + 1}: "${ref.title}" ---\n${ref.content.slice(0, 1500)}`,
  )

  const userMessage = [
    `Blog topic: ${topic}`,
    BLOG_VOICE,
    '',
    refs.length > 0 ? ['Style references (match this tone and structure):', ...refs].join('\n\n') : '',
    '',
    BLOG_INSTRUCTIONS,
  ]
    .filter(Boolean)
    .join('\n')

  const raw = await runDraft(userMessage, joinSystem(BLOG_INSTRUCTIONS))
  return parseJsonDraft<BlogDraft>(raw)
}

// ─── Gateway client ────────────────────────────────────────────────────────

interface GatewayConfig {
  serverUrl: string
  username: string
  password: string
}

interface GatewayPart {
  type: string
  text?: string
}

const GATEWAY_TIMEOUT_MS = 240000 // blog drafts measured 85s on free big-pickle; give headroom

const DISABLED_TOOLS = {
  bash: false,
  read: false,
  edit: false,
  write: false,
  patch: false,
  glob: false,
  grep: false,
  list: false,
  webfetch: false,
}

function getGatewayConfig(): GatewayConfig {
  const serverUrl = process.env.OPENCODE_SERVER_URL
  const password = process.env.OPENCODE_SERVER_PASSWORD

  if (!serverUrl || !password) {
    throw new Error('AI gateway unavailable')
  }

  return {
    serverUrl: serverUrl.replace(/\/+$/, ''),
    username: process.env.OPENCODE_SERVER_USERNAME || 'opencode',
    password,
  }
}

function authHeader(config: GatewayConfig): string {
  return `Basic ${Buffer.from(`${config.username}:${config.password}`).toString('base64')}`
}

async function createSession(config: GatewayConfig): Promise<string> {
  const response = await fetch(`${config.serverUrl}/session`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(config),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title: 'aliento-ai' }),
    signal: AbortSignal.timeout(GATEWAY_TIMEOUT_MS),
  })

  if (!response.ok) {
    throw new Error('AI gateway unavailable')
  }

  const data = (await response.json()) as { id?: string }

  if (!data.id) {
    throw new Error('AI gateway unavailable')
  }

  return data.id
}

async function sendGatewayMessage(
  config: GatewayConfig,
  sessionId: string,
  system: string,
  userText: string,
): Promise<string> {
  const response = await fetch(`${config.serverUrl}/session/${sessionId}/message`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(config),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      system,
      parts: [{ type: 'text', text: userText }],
      model: { providerID: 'opencode', modelID: 'big-pickle' },
      tools: DISABLED_TOOLS,
    }),
    signal: AbortSignal.timeout(GATEWAY_TIMEOUT_MS),
  })

  if (!response.ok) {
    throw new Error('AI gateway unavailable')
  }

  const data = (await response.json()) as { parts?: GatewayPart[] }
  const text = (data.parts ?? [])
    .filter((part) => part.type === 'text' && typeof part.text === 'string')
    .map((part) => part.text as string)
    .join('\n')
    .trim()

  if (!text) {
    throw new Error('AI gateway unavailable')
  }

  return text
}

/**
 * Full draft round-trip: session → pseudonymised message → token
 * restoration on the model's reply.
 */
async function runDraft(
  userMessage: string,
  system: string,
  knownPii?: KnownPatientPii,
): Promise<string> {
  const config = getGatewayConfig()
  const sessionId = await createSession(config)

  const pseudonymized = pseudonymizeText(userMessage, knownPii)
  const rawModelText = await sendGatewayMessage(config, sessionId, system, pseudonymized.text)

  return restoreTokens(rawModelText, pseudonymized.map)
}

// ─── Helpers ───────────────────────────────────────────────────────────────

/**
 * Cap questionnaire payloads sent to the shared free gateway — larger
 * prompts hit the latency ceiling and time out. 3000 chars keeps the
 * clinical signal (dates, symptoms, reason) while staying fast.
 */
function trimQuestionnaire(raw: string): string {
  return raw.length > 3000
    ? `${raw.slice(0, 3000)}\n…[questionnaire truncated for length]`
    : raw
}

function joinSystem(perTypeInstructions: string): string {
  return `${SHARED_SYSTEM_PROMPT}\n\n${perTypeInstructions}`
}

/**
 * Strip optional ```json fences the model sometimes wraps around its
 * answer, then parse — throwing a stable error message on failure so
 * callers can surface a single, safe status.
 */
function parseJsonDraft<T>(raw: string): T {
  const cleaned = raw.replace(/```json?/g, '').replace(/```/g, '').trim()

  try {
    return JSON.parse(cleaned) as T
  } catch {
    throw new Error('AI returned invalid JSON')
  }
}
